# Generated by Django 2.2.4 on 2020-11-02 10:50
import phonenumber_field.modelfields
import phonenumbers
from django.db import migrations


def parse_to_pure_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            pure_phone = phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_phone
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None,
                                                                 verbose_name='Нормализованный номер владельца'),
        ),
        migrations.RunPython(parse_to_pure_phonenumbers),
    ]
