# Generated by Django 2.2.4 on 2020-11-02 10:50
import phonenumbers
from django.db import migrations


def parse_to_pure_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        pure_phone = phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = pure_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(parse_to_pure_phonenumbers)
    ]
