# Generated by Django 2.2.4 on 2020-11-03 03:46

from django.db import migrations

from property.models import Owner


def copy_owners_from_flat_to_owner(apps, shcema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                    defaults={
                                        'owner_pure_phone': flat.owner_pure_phone,
                                    })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201102_2244'),
    ]

    operations = [
        migrations.RunPython(copy_owners_from_flat_to_owner),
    ]

