# Generated by Django 2.2.4 on 2020-11-03 04:24

from django.db import migrations

from property.models import Owner


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        owner, created = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                                     defaults={
                                                         'owner_pure_phone': flat.owner_pure_phone,
                                                     })
        owner.flats.add(flat.id)
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20201103_1046'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners),
    ]
